import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./index.css";
import "./App.css";
import "./normalize.css";
import Toast from "./_components/Toast/Toast";
// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pokedex",
  description: "Pokedex generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Toast />
      </body>
    </html>
  );
}
