import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./index.css";
import "./App.css";
import "./normalize.css";
import Toast from "./_components/Toast/Toast";
import SessionProvider from "./_components/SessionProvider";
import { getServerSession } from "next-auth";
import { authConfig } from "./auth.config";
// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pokedex",
  description: "Pokedex generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authConfig);
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>{children}</SessionProvider>
        <Toast />
      </body>
    </html>
  );
}
